apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        env: development
    spec:
      containers:
      - name: frontend
        image: gcr.io/secure-current-313023/frontend:v1
        ports:
        - containerPort: 4200
       
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4200
    protocol: TCP
  selector:
    app: frontend
